# Generated by Django 3.0.7 on 2020-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articel', '0005_auto_20200609_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_avatar'),
        ),
    ]
